# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NYTinOBJC' do
  # Comment the next line if you don't want to use dynamic frameworks
  
use_frameworks!
pod 'SDWebImage' , '~> 4.0'

  # Pods for NYTinOBJC

  target 'NYTinOBJCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTinOBJCUITests' do
    # Pods for testing
  end

end
